apiVersion : apps/v1
kind: Deployment
metadata:
  name: vishalprojectpython 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vishalprojectpython
  template:
    metadata:
      labels:
        app: vishalprojectpython 
    spec:
      containers:
        - name: vishalprojectpython 
          image: acrbox.azurecr.io/vishalprojectpython
          ports:
          - containerPort: 80